# Dependencies
highlighter:      rouge

# Permalinks
permalink: /:title/

# Setup
title:            Insolor
tagline:          # Описание в заголовке
description:      'Тут будет описание'
url: ""
baseurl: https://insolor.github.io

author:
  name:           'Insolor'
  url:            https://twitter.com/insolor

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:

disqus: insolor-github-io

google_analytics: UA-34037335-12
yandex_metrika: 48492119
