# Dependencies
highlighter:      rouge

# Permalinks
permalink: /:title/

# Setup
title:            Insolor
tagline:          'tagline'
description:      'Тут будет описание'
url: ""
baseurl: https://insolor.github.io

author:
  name:           'Insolor'
  url:            https://twitter.com/insolor

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:
